/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hnM9H3k63SE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs";

export function ComparisonSection() {
  return (
    <section
      key="1"
      className="w-full py-12 md:py-24 lg:py-32 flex justify-center items-center"
    >
      <div className="container px-4 md:px-6">
        <div className="mx-auto max-w-[90%]  lg:flex justify-evenly ">
          <Tabs
            className="rounded-lg p-2 drop-shadow-lg bg-white shadow-sm max-lg:mb-10 "
            defaultValue="include"
          >
            <TabsList className="flex items-center justify-between rounded-t-lg bg-gray-200 p-1">
              <TabsTrigger
                className="flex-1 drop-shadow-lg rounded-md py-2 px-4 text-xl font-medium transition-colors hover:bg-[#E2E9CA] data-[state=active]:bg-white data-[state=active]:text-gray-900"
                value="include"
              >
                Lo que incluye
              </TabsTrigger>
            </TabsList>
            <TabsContent
              className="data-[state=active]:p-6 flex flex-col gap-4 backdrop-blur-sm"
              value="include"
            >
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <BoltIcon className="h-6 w-6 text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Instructivo digital en formato PDF
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <FlameIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Acceso al video curso en YouTube.
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <SparklesIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Aprenderás sobre selección de ceras
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <ZapIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Aprenderás procedimientos, técnicas y manejo de temperaturas
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <BoltIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Veras el uso de colorantes y técnicas de decoración
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <FlameIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Y mucho mas
                </div>
              </div>
            </TabsContent>
          </Tabs>
          <Tabs
            className="rounded-lg p-2 drop-shadow-lg bg-white shadow-sm "
            defaultValue="require"
          >
            <TabsList className="flex items-center justify-between rounded-t-lg bg-gray-200 p-1">
              <TabsTrigger
                className="flex-1 drop-shadow-lg rounded-md py-2 px-4 text-xl font-medium transition-colors hover:bg-[#E2E9CA] data-[state=active]:bg-white data-[state=active]:text-gray-900"
                value="require"
              >
                Lo que necesitas
              </TabsTrigger>
            </TabsList>

            <TabsContent
              className="flex data-[state=active]:p-6  flex-col gap-4 backdrop-blur-sm"
              value="require"
            >
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <BoltIcon className="h-6 w-6 text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Un dispositivo con acceso a internet
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <FlameIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Cuenta de Youtube
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <SparklesIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Comprobante de pago por $5500
                </div>
              </div>
              <div className="flex items-center justify-start rounded-md bg-[#214E40] p-4">
                <ZapIcon className="h-6 w-6  text-gray-100" />
                <div className="px-5 text-gray-100 text-balance">
                  Si tenes todo esta lista para empezar a hacer tus propiar
                  velas
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </section>
  );
}

function BoltIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  );
}

function FlameIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z" />
    </svg>
  );
}

function SparklesIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
      <path d="M5 3v4" />
      <path d="M19 17v4" />
      <path d="M3 5h4" />
      <path d="M17 19h4" />
    </svg>
  );
}

function ZapIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z" />
    </svg>
  );
}
